### PR TITLE
asynchronuous pypi requests

### PR DESCRIPTION
**Pull request by mhindery**
Do requests for package versions on pypi in parallel using asyncio. This significantly speeds up execution. A comparison of running the tool on one of my requirements below where it speeds up from 8.5 seconds to 2.5 seconds. I also added some type annotations and other minor changes to `check_outdated.py` while I was at it.

pipoutdated_speedup

### CODE REVIEW

**Comment by mhindery** [comment]
Some notes:
- I used a dataclass here which was only added in python 3.7, so I bumped the version. If that's not ok, I can remove that again.
- The code coverage went down percentage-wise, because the file has slightly more lines of code now. The part which I changed wasn't tested before and still isn't. I don't think that's a blocking issue?

**Comment by eight04** [comment]
If we just want to parallel requests, we can simply push them to new threads. We also have to check if it is allowed to send parallel requests to pypi.

**Comment by mhindery** [comment]
The Requests session isn't threadsafe, so shouldn't be used in a parallel way, and asyncio with aiohttp is the new and better way over thread(pool)s and requests. Why would you go for the old way?

**Comment by eight04** [comment]
Because it will be a simple change. I'll check how aiohttp works.

**Pull request closed without merging**
